spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://mysql:3306/gateway?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: redis
      port: 6379

  rabbitmq:
    exchange: exchange.gateway.requests
    host: rabbitmq
    port: 5672
    username: root
    password: secret
    retry:
      interval: 500
      multiplier: 2
      max-interval: 5000
      max-attempts: 5

fixer:
  api:
    key: a86f332d748de9a5ee20e0444a7e1623
    url: http://data.fixer.io/api/latest
    base: EUR
  scheduler:
    interval: 3600000  # 1 hour in milliseconds

app:
  duplication-check:
    ttl-hours: 24